### ISSUE TITLE
[bug] Waterfall Chart Example Breaks

### ISSUE THREAD

**Issue by hydrosquall** [nteract/semiotic-docs#19]
The following error pops up in the console and the screen blanks out when navigating to this page using the build from the current `master` branch - I am guessing that this example might not be compatible with the current version (`1.20.2`) of Semiotic in some way.

- `localhost:3000/examples/waterfall-chart`
- Code: https://github.com/nteract/semiotic-docs/blob/master/src/examples/WaterfallChart.js

<a href="https://cl.ly/08e6330417e3" target="_blank"><img src="https://d2ddoduugvun08.cloudfront.net/items/2B0s1i2i0d1H1z3k3n2U/Image%202019-10-05%20at%207.15.02%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

**Comment by hydrosquall** [comment]
I downgraded Semiotic from `1.20.2` to `1.18.0`, and the example worked again. Going to `1.19.11` led to the same console error as with `1.20+`. As a result, I think something about the OrdinalFrame API changed in the between.

**Comment by emeeks** [comment]
Thanks for taking a look into this. I believe there's an updated version that works but just hasn't been deployed.

**Comment by hydrosquall** [comment]
Ah, great! My concern had been that if we deployed the current “master”
branch to the public URL, this example would stop working. However, if
there’s already a fix on another branch somewhere, then we probably want to
merge that before redeploying the site.

**Comment by hydrosquall** [comment]
Debugged a bit and I think this is what changed

- All of the layouts in https://github.com/nteract/semiotic/blob/4587fdd5c8424b0d0046e093c507b5431c7470a3/src/components/svg/pieceLayouts.tsx return arrays of `data` objects, like 

https://github.com/nteract/semiotic/blob/4587fdd5c8424b0d0046e093c507b5431c7470a3/src/components/svg/pieceLayouts.tsx#L771-L779

- The custom waterfall layouts return actual `ReactElements`, like

https://github.com/nteract/semiotic-docs/blob/682b3936a01705349187e3909c1ed537fd5c23e6/src/examples/WaterfallChart.js#L209-L215

**Comment by hydrosquall** [comment]
*Update*

- You're right, https://github.com/nteract/semiotic/commit/56577bee7d7a3ad5172213e829cc34e9667698cd#diff-bd358c5975a9c00b32a3addf8402032c fixes this issue.

Bumping the version of semiotic in the docs to `1.20.3` the example, PR incoming.
