### ISSUE TITLE
yarn.lock points to internal netflix npm url

### ISSUE THREAD

**Issue by BenRussert** [nteract/semiotic-docs#2]
I was trying out the repo locally and found that  `yarn` failed to install silently. To fix, I deleted `yarn.lock` and ran `yarn` again to generate a new file that removed the internal urls.

Love these docs, BTW!

**Comment by willingc** [comment]
@emeeks @susielu Is there any reason not to update the `yarn.lock` to remove the Netflix URLs?

**Comment by susielu** [comment]
Thanks yes I just updated this, good catch.
